### ISSUE TITLE
Protected routes using admin check and lazy loading

### ISSUE THREAD

**Issue by babycourageous** [lukeed/svelte-demo#12]
Hi @lukeed ! 

I'm trying to apply your recommendation here - https://github.com/lukeed/navaid/issues/22 - to this demo implementation that uses dynamic imports. 

I'm curious how I might accomplish protected routes using that pattern.

Something like the following: 

```js
function onAdmin(route) {
     return (obj) => {
       if (!$isLoggedIn) {
         console.log('not authorized')
         router.route('/pages/Login.svelte', true)
       } else {
         console.log('is logged in')
         params = obj || {}
         run(import(`pages/${Route}`))
       }
     }
  }

router
    .on('/', () => run(import('Home.svelte')))
    .on('noway', onAdmin('NoWay.svelte'))
    .on('ok', run(import('Way.svelte')))
    .listen()
```

`run` is the same code from the demo. The first pare of `if` statement works if you are not logged in. However if you are... it results in the following error: 

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

new:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:5000/pages/NoWay.svelte
```

Reverting to your original demo (without `onAdmin` check) works fine.

(As a side ask, is `router.route('/pages/Login.svelte', true)` how `navaid` does Redirects?

Thanks so much!

**Comment by lukeed** [comment]
Hey, so what's probably happening is your `Route` is uninitialized and so you're being sent down aa bad response. The current version of `sirv-cli` sends down the `index.html` instead of a 404 when the `--single` flag is enabled, so this makes it a little confusing initially. This explains the `responded with a non-JavaScript MIME type of "text/html"` error you're seeing.  (This sirv behavior has been fixed in the next version)

There's also the fact that you're always better off statically describing your dynamic imports up front. This allows Rollup to split and link them 100% of the time. Actually, this is probably the main reason for your issue:

Even if `Route` were correct (say, "Blog.svelte"), at runtime "pages/Blog.svelte" means nothing since it would have been transformed into a different filepath entirely. Dynamically-constructed dynamic imports should only be done for absolute, known URLs.

I put together a quick demo for you in the [`demo/guards`](https://github.com/lukeed/svelte-demo/tree/demo/guards) branch.

It implements auth-guards at two levels: user-vs-not, admin-vs-user.
It links the Nav to the user status (conditionally revealing nav items), but if you tried to navigate to `/private` directly in your address bar, users will be kicked to `/forbidden` and non-users will be kicked to the `/login` page.

There are, of course, a couple ways to do it, but I just wanted to show the simplest of them that aligned with your initial example.

> As a side ask, is `router.route('/pages/Login.svelte', true)` how navaid does Redirects?

Yes, especially if you want replace the current URL. In other words, the `true` means that hitting the Back button won't go back to the same page. I used this in my example branch 👍 

Hope it helps~! Closing for now, but feel free to follow up here :)

**Comment by babycourageous** [comment]
You're awesome! Thank you.
I sincerely love all your projects. Big fan of your work. I keep meaning to contribute on a small scale (heheh) to `polka` but get sidetracked or hit road blocks. Anyway - 

That makes a whole lotta sense and what i figured was going on. I was futzing around and got KINDA close to ya... 

```js
    .on('noway', onAdmin(run(import('pages/NoWay.svelte'))))
```

I didn't even see that other branch in there. Whoops.

Again - thanks so much and if I hit a snag I'll poke.

**Comment by lukeed** [comment]
Thank you :) 
The branch wasn't there until about 20 minutes ago. Made it for you!

**Comment by babycourageous** [comment]
Oh wow - high fives!
